name: Bug report
description: Create a report to help us improve the game
labels: bug

body:
    - type: markdown
      attributes:
        value: |
          ## Please fill out the form below with as much information as possible.
          ### Attach screenshots if needed to help explain the issue.
    - type: input
      id: distro
      attributes:
        label: OS & Version
        description: The operating system and version in use, or if web the web browser in use.
      validations:
        required: true
    - type: input
      id: gameversion
      attributes:
        label: Game Version
        description: The version of of the game being used.
      validations:
        required: true
    - type: textarea
      id: description
      attributes:
        label: Bug description
        description: A clear and concise description of what the bug is.
      validations:
        required: true
    - type: textarea
      id: reproduce
      attributes:
        label: Steps To Reproduce
        description: Describe the steps to reproduce the bug.
        placeholder: |
            1. …
            2. …
            3. …
      validations:
        required: true
    - type: textarea
      id: expected
      attributes:
        label: Expected Behavior
        description: Describe the expected behavior
      validations:
        required: true
    - type: textarea
      id: additional
      attributes:
        label: Additional Context
        description: Provide any additional details that do not fit in the other questions.
    - type: textarea
      id: logs
      attributes:
        label: Relevant log output
        description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        render: shell
