name: Build Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Setup wine
      id: wine_install
      run: |
        sudo apt install wine64
        echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
    - name: Setup Android Debug Keystore
      uses: akiojin/decode-base64-github-action@v0.1.0
      with:
        base64: ${{ secrets.ANDROID_DEBUG_KEYSTORE }}
        output-path: debug.keystore
    - name: Export Game
      id: export
      uses: firebelley/godot-export@v5.2.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
        export_debug: true
        cache: true
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: ${{ steps.export.outputs.archive_directory }}/LinuxX11.zip
    - name: Upload Web Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web
        path: ${{ steps.export.outputs.archive_directory }}/Web.zip
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ${{ steps.export.outputs.archive_directory }}/"Windows Desktop.zip"
    - name: Upload Android Artifact
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: ${{ steps.export.outputs.archive_directory }}/Android.zip
