name: Build Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Export Game
      id: export
      uses: firebelley/godot-export@v5.2.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: export
        path: ${{ steps.export.outputs.archive_directory }}/*
